In [1]:
%run proclus.ipynb
%run plotter.ipynb
%run arffreader.ipynb
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats.stats import pearsonr
#import adjrand

# Test to see if there is a correlation between the
# proclus objective function and the adjusted rand index

X, sup = readarff("data/highdataproclus.arff")

NRUNS = 15

objs = np.zeros(NRUNS) # objective function results
adjs = np.zeros(NRUNS) # adjusted rand index results

print ("Beginning runs...")

for i in xrange(NRUNS):
	rseed = np.random.randint(low = 0, high = 1239831)
	print(">>> Run %d/%d using seed %d" % (i + 1, NRUNS, rseed))
	M, D, A = proclus(X, k = 7, l = 2, seed = rseed)
	objs[i] = evaluateClusters(X, A, D, M)
	#adjs[i] = adjrand.computeAdjustedRandIndex(A, sup)

print("Finished runs...")

sidx = np.argsort(objs)

plt.clf()
plt.plot(objs[sidx], adjs[sidx], 'bo-')
plt.xlabel("Objective function results")
plt.ylabel("Adjusted Rand Index")
plt.show()
plt.draw()

#print "Pearson correlation: %.4f" % pearsonr(objs[sidx], adjs[sidx])[0]


Beginning runs...
>>> Run 1/15 using seed 23902
bad medoids:
[592, 1403, 631]
old mcurr:
[ 576  592  950 1630  925 1403  631]
new mcurr:
[ 576  742  925  950 1115 1630 1789]
finished iter: 1
bad medoids:
[1115]
old mcurr:
[ 576  742  925  950 1115 1630 1789]
new mcurr:
[ 576  592  742  925  950 1630 1789]
finished iter: 2
finished iter: 3
finished iterative phase...
>>> Run 2/15 using seed 1034995
bad medoids:
[1840]
old mcurr:
[ 467 1728  699 1308 1123 1840  271]
new mcurr:
[ 271  467  699 1123 1308 1449 1728]
finished iter: 1
bad medoids:
[1308]
old mcurr:
[ 271  467  699 1123 1308 1449 1728]
new mcurr:
[ 271  467  699 1123 1449 1728 1840]
finished iter: 2
finished iter: 3
finished iterative phase...
>>> Run 3/15 using seed 809210
bad medoids:
[211, 1902]
old mcurr:
[ 130  757 1902 1388   28  211  231]
new mcurr:
[  19   28  130  231  467  757 1388]
finished iter: 1
finished iter: 2
finished iterative phase...
>>> Run 4/15 using seed 876915
bad medoids:
[1403]
old mcurr:
[1266 1992 1

<Figure size 640x480 with 1 Axes>

Pearson correlation: nan


C:\Users\Ingenieur\Anaconda2\lib\site-packages\scipy\stats\stats.py:3038: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den
C:\Users\Ingenieur\Anaconda2\lib\site-packages\scipy\stats\stats.py:3047: RuntimeWarning: invalid value encountered in double_scalars
  t_squared = r**2 * (df / ((1.0 - r) * (1.0 + r)))
